### PR TITLE
migrates to MPS 2019.2.3

### PR DESCRIPTION
**Pull request by szabta89**
All straightforward.

### CODE REVIEW

**Comment by justinhorton** [comment]
> java.lang.UnsupportedClassVersionError: jetbrains/mps/build/ant/ModuleJarDataType has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Looks like we need to update the CI build to use Java 11.

It would be good to also update https://github.com/Workday/mps-code-reviewer#prerequisites to indicate the Java 11 requirement.

@szabta89 do you know if there's a more elegant way to run this build locally than setting `JAVA_HOME` to JDK11 (since we're still using JDK8 for everyday development)? The ant script generation uses `JAVA_HOME` directly and I'm unsure how to pass that argument from the command line --> gradle task --> ant execution.

**Comment by ty1824** [comment]
The travis.yml file will need to have the JDK updated to 11 for this to build properly.

**Comment by ty1824** [comment]
> @szabta89 do you know if there's a more elegant way to run this build locally than setting `JAVA_HOME` to JDK11 (since we're still using JDK8 for everyday development)? The ant script generation uses `JAVA_HOME` directly and I'm unsure how to pass that argument from the command line --> gradle task --> ant execution.

We could reconfigure the gradle script to support supplying the java version differently - Environment Variables can be passed to the `exec` task

**Comment by szabta89** [comment]
> > java.lang.UnsupportedClassVersionError: jetbrains/mps/build/ant/ModuleJarDataType has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> 
> Looks like we need to update the CI build to use Java 11.
> 
> It would be good to also update https://github.com/Workday/mps-code-reviewer#prerequisites to indicate the Java 11 requirement.
> 
> @szabta89 do you know if there's a more elegant way to run this build locally than setting `JAVA_HOME` to JDK11 (since we're still using JDK8 for everyday development)? The ant script generation uses `JAVA_HOME` directly and I'm unsure how to pass that argument from the command line --> gradle task --> ant execution.

This is a good point. We agreed with @ty1824 that I will address this issue in a followup PR, so that I can get started with the migration of dependent projects.

**Pull request merged**
